ssh

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,30 +1,29 @@
 #!/usr/bin/env bash
 # A Script that displays information and subdomains
-
-print_info() {
+# shellcheck case SC2086 ignored
+show_subdomain_info() {
     domain="$1"
     subdomain="$2"
-
-    if [ -z "$subdomain" ]; then
-        subdomains=(www lb-01 web-01 web-02)
-    else
-        subdomains=("$subdomain")
-    fi
-
-    for sub in "${subdomains[@]}"; do
-        output=$(nslookup -type=A "$sub.$domain" | awk '/^Name:/ {print $2} /^Address:/ {print $2}')
-        echo "The subdomain $sub is a A record and points to $output"
-    done
+    dig_output="$(dig "$subdomain.$domain")"
+    record_type="$(echo "$dig_output" | awk '/ANSWER SECTION:/{getline; print $4}')"
+    ip_address="$(echo "$dig_output" | awk '/ANSWER SECTION:/{getline; print $5}')"
+    printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record_type" "$ip_address"
 }
 
-if [ $# -eq 1 ]; then
-    domain="$1"
-    print_info "$domain"
-elif [ $# -eq 2 ]; then
-    domain="$1"
-    subdomain="$2"
-    print_info "$domain" "$subdomain"
-else
-    echo "Usage: $0 <domain> [subdomain]"
+if [ -z "$1" ]; then
+    echo "Please provide a domain name as the first argument"
     exit 1
+fi
+
+if [ -n "$2" ] && ! [[ "$2" =~ ^(www|lb-01|web-01|web-02)$ ]]; then
+    echo "Invalid subdomain name. Allowed values are: www, lb-01, web-01, web-02"
+    exit 1
+fi
+
+if [ -n "$2" ]; then
+    show_subdomain_info "$1" "$2"
+else
+    for subdomain in www lb-01 web-01 web-02; do
+        show_subdomain_info "$1" "$subdomain"
+    done
 fi
